### ISSUE TITLE
Địa chỉ bị lỗi không đặt hàng được

### ISSUE THREAD

**Issue by hhloi** [binhle410/tuv-corp#1]
Không sửa thông tin địa chỉ để đặt hàng được
![image](https://cloud.githubusercontent.com/assets/3298194/5642950/92302fbc-9684-11e4-828a-ea649024c2b5.png)

**Comment by binhle410** [comment]
Fixed bằng cách thêm address_alias vào theme file 
	<div class="required form-group" id="adress_alias">
			<label for="alias">{l s='Please assign an address title for future reference.'} <sup>*</sup></label>
			<input type="text" id="alias" class="is_required validate form-control" data-validate="{$address_validation.alias.validate}" name="alias" value="{if isset($smarty.post.alias)}{$smarty.post.alias}{else if isset($address->alias)}{$address->alias|escape:'html':'UTF-8'}{elseif !$select_address}{l s='My address'}{/if}" />
		</div>
